import React from 'react'

function About(props) {
  return (
    <div style={{color:props.mode === `dark`?`white`:`gray` }}>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean euismod elementum nisi quis eleifend quam adipiscing. Aliquam sem et tortor consequat. Nunc sed id semper risus in hendrerit gravida rutrum quisque. Egestas erat imperdiet sed euismod nisi porta lorem mollis. Nisi est sit amet facilisis magna etiam tempor orci eu. Aliquam ultrices sagittis orci a scelerisque. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Dis parturient montes nascetur ridiculus mus. Gravida cum sociis natoque penatibus. Massa sed elementum tempus egestas. Vulputate mi sit amet mauris commodo. Dis parturient montes nascetur ridiculus mus mauris vitae. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Id interdum velit laoreet id donec ultrices. Tellus cras adipiscing enim eu turpis egestas pretium aenean pharetra. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim.</p>

      <p>Ultrices vitae auctor eu augue ut lectus arcu bibendum. Aliquam faucibus purus in massa tempor nec. Mi quis hendrerit dolor magna eget est. Ut venenatis tellus in metus vulputate eu. Nunc aliquet bibendum enim facilisis gravida neque convallis. Non diam phasellus vestibulum lorem. Placerat vestibulum lectus mauris ultrices eros in cursus. Sed risus ultricies tristique nulla aliquet enim. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam quis. Quisque egestas diam in arcu cursus euismod quis viverra nibh. Lobortis scelerisque fermentum dui faucibus in. Velit euismod in pellentesque massa placerat. At consectetur lorem donec massa sapien faucibus. Lectus nulla at volutpat diam. Quam adipiscing vitae proin sagittis nisl. Tempus urna et pharetra pharetra massa massa ultricies mi. Justo nec ultrices dui sapien. Nulla facilisi nullam vehicula ipsum a arcu cursus. Non arcu risus quis varius quam quisque.</p>

      <p>Id diam vel quam elementum pulvinar. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sollicitudin nibh sit amet commodo nulla facilisi. Sit amet risus nullam eget felis eget. Amet luctus venenatis lectus magna fringilla urna. Condimentum mattis pellentesque id nibh tortor id aliquet lectus proin. A iaculis at erat pellentesque adipiscing. Id eu nisl nunc mi ipsum faucibus. Etiam sit amet nisl purus in mollis nunc. Leo urna molestie at elementum. Augue ut lectus arcu bibendum at varius vel pharetra vel. Proin sed libero enim sed faucibus turpis in eu. Posuere lorem ipsum dolor sit amet. Augue eget arcu dictum varius duis at consectetur lorem donec. Dignissim sodales ut eu sem integer vitae justo eget. Gravida dictum fusce ut placerat. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis.</p>

      <p>Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Viverra maecenas accumsan lacus vel facilisis volutpat est velit egestas. Varius morbi enim nunc faucibus a pellentesque. Mattis rhoncus urna neque viverra justo nec. Urna nec tincidunt praesent semper. Pretium lectus quam id leo in vitae turpis massa. Vel facilisis volutpat est velit egestas dui id ornare arcu. Lacus laoreet non curabitur gravida arcu ac tortor dignissim. Quis auctor elit sed vulputate mi sit amet mauris commodo. In ante metus dictum at tempor commodo ullamcorper a.</p>

      <p>Porta non pulvinar neque laoreet suspendisse interdum. Elit pellentesque habitant morbi tristique senectus. Id eu nisl nunc mi ipsum faucibus. Vitae sapien pellentesque habitant morbi tristique. Diam vulputate ut pharetra sit amet. Sed sed risus pretium quam. Ultrices gravida dictum fusce ut placerat. Sapien faucibus et molestie ac. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Dolor purus non enim praesent elementum facilisis leo vel fringilla. Tellus in hac habitasse platea dictumst. Mauris a diam maecenas sed. Vel pretium lectus quam id leo in vitae turpis massa. Non enim praesent elementum facilisis leo vel fringilla est ullamcorper.</p>
    </div>
  )
}

export default About
